### ISSUE TITLE
potential parsing error on large groups

### ISSUE THREAD

**Issue by elevenchars** [rhgrant10/Groupy#49]
Trying to run the example code on the documentation,

```python3
for group in client.groups.list_all():
        print(group.name)
```

throws a `groupy.exceptions.InvalidJsonError`. However, when I run this instead:

```python3
for group in client.groups.list(omit="membership").autopage():
  print(group.name)
```

it runs successfully. This leads me to think that large user counts cause the JSON parsing to fail. I am in quite a few large groups (1800+, 700+, multiple 100+) which I think may be causing the issue.

**Comment by elevenchars** [comment]
Python version: 3.7.0
Groupy version: 0.10.2
OS: MacOS 10.14

**Comment by rhgrant10** [comment]
Yeah this is a known issue with the API :-(

There's a maximum response size so groups with tons of members can trigger this problem. It's not necessarily predictable either since groups are sorted by last updated time. Two large groups might update and be in the same page of results, but they might not and instead be on different pages.

You can also omit memberships when using `list_all` by the way. As always just be sure to call `refresh_from_server` on the group before working with its memberships.
