### ISSUE TITLE
API Token Validation

### ISSUE THREAD

**Issue by npjg** [rhgrant10/Groupy#53]
The documentation recommends "[checking] that your API token is correct just before you use it to create a Groupy client." Should token validation become a part of a Groupy client's construction? The client could, for instance, attempt to read the user's profile and raise an `UnauthorizedError` if the server returns a 401. The client would only be created if the token passes this validation check.

**Comment by rhgrant10** [comment]
Interesting question. I don't think there's enough value in that functionality primarily because the API token is static. Also I'm a fan of garbage in, garbage out. Really that step was added to the directions as a sanity check that helped prevent a bit of confusion when using the API for the first time. Likely the biggest impact would be a sudden need for users to try/except the client creation itself, which is a significant departure from existing behavior. Also note it would not catch all situations involving an invalid token because the account could change server-side.

If you want to explicitly check the token before making your first "real" request I would recommend simply wrapping your client creation in a function and use the method you outlined above.

**Comment by npjg** [comment]
Understood.
