### ISSUE TITLE
Can't create multiple bots with no callback url

### ISSUE THREAD

**Issue by ntsirakis** [rhgrant10/Groupy#55]
This was working for me a few weeks ago. My code is the following (shaved down for brevity):

`
self._client = Client.from_token(token)

self._bots_manager = Bots(self._client.session)

self._bots_manager.create('My-Bot', self._group.group_id) # group ID has been verified
`

Exception(s) caught:
`
received a bad response
Traceback (most recent call last):
  File "<redacted>/groupy/session.py", line 28, in request
    response.raise_for_status()
  File "<redacted>/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.groupme.com/v3/bots
Traceback (most recent call last):
  File "<redacted>/groupy/session.py", line 28, in request
    response.raise_for_status()
  File "<redacted>/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.groupme.com/v3/bots

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "myproj.py", line 25, in <module>
    bot = MyBot()
  File "myproj.py", line 16, in __init__
    self._initialize_bot()
  File "myproj.py", line 20, in _initialize_bot
    self._bot = self._groupme.get_bot('My-Bot')
  File "<redacted>/src/groupme.py", line 58, in get_bot
    self._bots_manager.create(name, self._group.group_id)
  File "<redacted>/groupy/api/bots.py", line 42, in create
    response = self.session.post(self.url, json=payload)
  File "<redacted>/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "<redacted>/groupy/session.py", line 32, in request
    raise exceptions.BadResponse(response) from e
groupy.exceptions.BadResponse: HTTP 400: Callback url callback url  already registered for group
`

**Comment by rhgrant10** [comment]
Hi @ntsirakis, that error message indicates that the callback url is already in use for a bot that's in that group. Each group and callback url combination must be unique.

**Comment by ntsirakis** [comment]
@rhgrant10 even if the callback URL is None for both bots?

**Comment by rhgrant10** [comment]
@ntsirakis hm, no callbacks is an interesting wrinkle. I tested this and found it to be true against both the API and the web UI at https://dev.groupme.com/bots, so it seems that it's not a problem with the Groupy client itself.

That being said, I've started a conversation with the devs on their support email to determine whether this is intentional design or the byproduct of a simple unique constraint on a database column.

I played around with the API and the web UI a bit attempting to make multiple bots in a group with no callback url. Because the web UI defaults the callback to an empty string and my client defaults to a null callback, I was only technically successful. Creating more than two in this way appears impossible since tests reveal null, empty string, and a valid URI are the only values allowed.

I made sure to ask the devs whether this behavior in the API changed recently, but I'd like to rule out the possibility that there actually exists a way to create two such bots using the API. You mentioned that this was working a few weeks back... may I also ask which version of Groupy you were using then and which version you are using now?

**Comment by ntsirakis** [comment]
@rhgrant10 thanks for looking into it! The version of Groupy should not have changed, I'm currently on 0.10.3. Very interesting point about the distinction between null and empty string; I thought I was able to work around the issue by creating the bot with the web UI, but I hadn't tried making a third bot. That does indeed fail, darn. Let me know what you find.

**Comment by ntsirakis** [comment]
@rhgrant10 Just realizing that my attempt to make the bot a few weeks ago did not involve a second, already-established bot, so that's why I had no issues. I didn't realize at the time of my initial post that it was a multi-bot issue. This callback issue may have been present for a while, then.

**Comment by rhgrant10** [comment]
@ntsirakis okay yeah that makes sense. This was a weird issue... took me a while to figure it out 😂 In that case, I'll go ahead a close this issue. If/when GroupMe devs respond I'll update this issue with the info.
